const WORDS_DATA = [
  // ===== Day 1 =====
  { id: 1, kanji: "間", hiragana: "あいだ", meaning: "사이, 간격", day: 1 },
  { id: 2, kanji: "秋", hiragana: "あき", meaning: "가을", day: 1 },
  { id: 3, kanji: "朝", hiragana: "あさ", meaning: "아침", day: 1 },
  { id: 4, kanji: "朝ご飯", hiragana: "あさごはん", meaning: "아침밥, 아침 식사", day: 1 },
  { id: 5, kanji: "あさって", hiragana: "あさって", meaning: "모레", day: 1 },
  { id: 6, kanji: "足", hiragana: "あし", meaning: "발, 다리", day: 1 },
  { id: 7, kanji: "明日", hiragana: "あした", meaning: "내일", day: 1 },
  { id: 8, kanji: "あそこ", hiragana: "あそこ", meaning: "저기, 저곳", day: 1 },
  { id: 9, kanji: "頭", hiragana: "あたま", meaning: "머리", day: 1 },
  { id: 10, kanji: "あちら", hiragana: "あちら", meaning: "저쪽, 저분", day: 1 },
  { id: 11, kanji: "後", hiragana: "あと", meaning: "뒤, 나중", day: 1 },
  { id: 12, kanji: "あなた", hiragana: "あなた", meaning: "당신, 너", day: 1 },
  { id: 13, kanji: "兄", hiragana: "あに", meaning: "(내) 형, 오빠", day: 1 },
  { id: 14, kanji: "姉", hiragana: "あね", meaning: "(내) 언니, 누나", day: 1 },
  { id: 15, kanji: "雨", hiragana: "あめ", meaning: "비", day: 1 },
  { id: 16, kanji: "家", hiragana: "いえ", meaning: "집", day: 1 },
  { id: 17, kanji: "いくつ", hiragana: "いくつ", meaning: "몇 개, 몇 살", day: 1 },
  { id: 18, kanji: "いくら", hiragana: "いくら", meaning: "얼마", day: 1 },
  { id: 19, kanji: "池", hiragana: "いけ", meaning: "연못", day: 1 },
  { id: 20, kanji: "医者", hiragana: "いしゃ", meaning: "의사", day: 1 },
  { id: 21, kanji: "いす", hiragana: "いす", meaning: "의자", day: 1 },
  { id: 22, kanji: "一日", hiragana: "いちにち", meaning: "하루, 1일", day: 1 },
  { id: 23, kanji: "一週間", hiragana: "いっしゅうかん", meaning: "일주일", day: 1 },
  { id: 24, kanji: "犬", hiragana: "いぬ", meaning: "개", day: 1 },
  { id: 25, kanji: "今", hiragana: "いま", meaning: "지금", day: 1 },
  { id: 26, kanji: "意味", hiragana: "いみ", meaning: "의미, 뜻", day: 1 },
  { id: 27, kanji: "妹", hiragana: "いもうと", meaning: "(내) 여동생", day: 1 },

  // ===== Day 2 =====
  { id: 28, kanji: "入り口", hiragana: "いりぐち", meaning: "입구", day: 2 },
  { id: 29, kanji: "色", hiragana: "いろ", meaning: "색, 색깔", day: 2 },
  { id: 30, kanji: "上", hiragana: "うえ", meaning: "위", day: 2 },
  { id: 31, kanji: "後ろ", hiragana: "うしろ", meaning: "뒤, 후방", day: 2 },
  { id: 32, kanji: "歌", hiragana: "うた", meaning: "노래", day: 2 },
  { id: 33, kanji: "海", hiragana: "うみ", meaning: "바다", day: 2 },
  { id: 34, kanji: "上着", hiragana: "うわぎ", meaning: "겉옷, 상의", day: 2 },
  { id: 35, kanji: "運動", hiragana: "うんどう", meaning: "운동", day: 2 },
  { id: 36, kanji: "絵", hiragana: "え", meaning: "그림", day: 2 },
  { id: 37, kanji: "映画", hiragana: "えいが", meaning: "영화", day: 2 },
  { id: 38, kanji: "英語", hiragana: "えいご", meaning: "영어", day: 2 },
  { id: 39, kanji: "駅", hiragana: "えき", meaning: "역", day: 2 },
  { id: 40, kanji: "円", hiragana: "えん", meaning: "엔 (일본 화폐)", day: 2 },
  { id: 41, kanji: "鉛筆", hiragana: "えんぴつ", meaning: "연필", day: 2 },
  { id: 42, kanji: "お母さん", hiragana: "おかあさん", meaning: "어머니, 엄마", day: 2 },
  { id: 43, kanji: "お菓子", hiragana: "おかし", meaning: "과자", day: 2 },
  { id: 44, kanji: "お金", hiragana: "おかね", meaning: "돈", day: 2 },
  { id: 45, kanji: "お客さん", hiragana: "おきゃくさん", meaning: "손님", day: 2 },
  { id: 46, kanji: "奥さん", hiragana: "おくさん", meaning: "(남의) 아내, 사모님", day: 2 },
  { id: 47, kanji: "お酒", hiragana: "おさけ", meaning: "술", day: 2 },
  { id: 48, kanji: "お皿", hiragana: "おさら", meaning: "접시", day: 2 },
  { id: 49, kanji: "おじいさん", hiragana: "おじいさん", meaning: "할아버지", day: 2 },
  { id: 50, kanji: "おじさん", hiragana: "おじさん", meaning: "아저씨, 삼촌", day: 2 },
  { id: 51, kanji: "お茶", hiragana: "おちゃ", meaning: "차, 녹차", day: 2 },
  { id: 52, kanji: "お父さん", hiragana: "おとうさん", meaning: "아버지, 아빠", day: 2 },
  { id: 53, kanji: "弟", hiragana: "おとうと", meaning: "(내) 남동생", day: 2 },
  { id: 54, kanji: "男", hiragana: "おとこ", meaning: "남자", day: 2 },
  { id: 55, kanji: "男の子", hiragana: "おとこのこ", meaning: "남자아이, 남자애", day: 2 },

  // ===== Day 3 =====
  { id: 56, kanji: "男の人", hiragana: "おとこのひと", meaning: "남자, 남성", day: 3 },
  { id: 57, kanji: "一昨日", hiragana: "おととい", meaning: "그저께", day: 3 },
  { id: 58, kanji: "一昨年", hiragana: "おととし", meaning: "재작년", day: 3 },
  { id: 59, kanji: "大人", hiragana: "おとな", meaning: "어른, 성인", day: 3 },
  { id: 60, kanji: "お腹", hiragana: "おなか", meaning: "배 (복부)", day: 3 },
  { id: 61, kanji: "お兄さん", hiragana: "おにいさん", meaning: "(남의) 형, 오빠", day: 3 },
  { id: 62, kanji: "お姉さん", hiragana: "おねえさん", meaning: "(남의) 누나, 언니", day: 3 },
  { id: 63, kanji: "おばあさん", hiragana: "おばあさん", meaning: "할머니", day: 3 },
  { id: 64, kanji: "おばさん", hiragana: "おばさん", meaning: "아주머니, 이모, 고모", day: 3 },
  { id: 65, kanji: "お風呂", hiragana: "おふろ", meaning: "목욕, 욕조", day: 3 },
  { id: 66, kanji: "お弁当", hiragana: "おべんとう", meaning: "도시락", day: 3 },
  { id: 67, kanji: "おまわりさん", hiragana: "おまわりさん", meaning: "경찰관", day: 3 },
  { id: 68, kanji: "音楽", hiragana: "おんがく", meaning: "음악", day: 3 },
  { id: 69, kanji: "女", hiragana: "おんな", meaning: "여자", day: 3 },
  { id: 70, kanji: "女の子", hiragana: "おんなのこ", meaning: "여자아이, 여자애", day: 3 },
  { id: 71, kanji: "女の人", hiragana: "おんなのひと", meaning: "여자, 여성", day: 3 },
  { id: 72, kanji: "会議", hiragana: "かいぎ", meaning: "회의", day: 3 },
  { id: 73, kanji: "外国", hiragana: "がいこく", meaning: "외국", day: 3 },
  { id: 74, kanji: "外国人", hiragana: "がいこくじん", meaning: "외국인", day: 3 },
  { id: 75, kanji: "会社", hiragana: "かいしゃ", meaning: "회사", day: 3 },
  { id: 76, kanji: "会社員", hiragana: "かいしゃいん", meaning: "회사원", day: 3 },
  { id: 77, kanji: "階段", hiragana: "かいだん", meaning: "계단", day: 3 },
  { id: 78, kanji: "買い物", hiragana: "かいもの", meaning: "쇼핑, 장보기", day: 3 },
  { id: 79, kanji: "顔", hiragana: "かお", meaning: "얼굴", day: 3 },
  { id: 80, kanji: "かぎ", hiragana: "かぎ", meaning: "열쇠", day: 3 },
  { id: 81, kanji: "学生", hiragana: "がくせい", meaning: "학생 (대학생)", day: 3 },
  { id: 82, kanji: "かさ", hiragana: "かさ", meaning: "우산", day: 3 },
  { id: 83, kanji: "風", hiragana: "かぜ", meaning: "바람", day: 3 },

  // ===== Day 4 =====
  { id: 84, kanji: "風邪", hiragana: "かぜ", meaning: "감기", day: 4 },
  { id: 85, kanji: "家族", hiragana: "かぞく", meaning: "가족", day: 4 },
  { id: 86, kanji: "学校", hiragana: "がっこう", meaning: "학교", day: 4 },
  { id: 87, kanji: "かばん", hiragana: "かばん", meaning: "가방", day: 4 },
  { id: 88, kanji: "花瓶", hiragana: "かびん", meaning: "꽃병", day: 4 },
  { id: 89, kanji: "紙", hiragana: "かみ", meaning: "종이", day: 4 },
  { id: 90, kanji: "体", hiragana: "からだ", meaning: "몸, 신체", day: 4 },
  { id: 91, kanji: "川", hiragana: "かわ", meaning: "강, 하천", day: 4 },
  { id: 92, kanji: "漢字", hiragana: "かんじ", meaning: "한자", day: 4 },
  { id: 93, kanji: "木", hiragana: "き", meaning: "나무", day: 4 },
  { id: 94, kanji: "北", hiragana: "きた", meaning: "북쪽", day: 4 },
  { id: 95, kanji: "北側", hiragana: "きたがわ", meaning: "북쪽 방향", day: 4 },
  { id: 96, kanji: "切手", hiragana: "きって", meaning: "우표", day: 4 },
  { id: 97, kanji: "切符", hiragana: "きっぷ", meaning: "표, 티켓", day: 4 },
  { id: 98, kanji: "昨日", hiragana: "きのう", meaning: "어제", day: 4 },
  { id: 99, kanji: "牛肉", hiragana: "ぎゅうにく", meaning: "쇠고기", day: 4 },
  { id: 100, kanji: "牛乳", hiragana: "ぎゅうにゅう", meaning: "우유", day: 4 },
  { id: 101, kanji: "今日", hiragana: "きょう", meaning: "오늘", day: 4 },
  { id: 102, kanji: "教室", hiragana: "きょうしつ", meaning: "교실", day: 4 },
  { id: 103, kanji: "兄弟", hiragana: "きょうだい", meaning: "형제, 남매", day: 4 },
  { id: 104, kanji: "去年", hiragana: "きょねん", meaning: "작년", day: 4 },
  { id: 105, kanji: "銀行", hiragana: "ぎんこう", meaning: "은행", day: 4 },
  { id: 106, kanji: "薬", hiragana: "くすり", meaning: "약", day: 4 },
  { id: 107, kanji: "果物", hiragana: "くだもの", meaning: "과일", day: 4 },
  { id: 108, kanji: "口", hiragana: "くち", meaning: "입", day: 4 },
  { id: 109, kanji: "靴", hiragana: "くつ", meaning: "신발, 구두", day: 4 },
  { id: 110, kanji: "靴下", hiragana: "くつした", meaning: "양말", day: 4 },
  { id: 111, kanji: "国", hiragana: "くに", meaning: "나라, 국가", day: 4 },

  // ===== Day 5 =====
  { id: 112, kanji: "車", hiragana: "くるま", meaning: "차, 자동차", day: 5 },
  { id: 113, kanji: "警官", hiragana: "けいかん", meaning: "경찰관", day: 5 },
  { id: 114, kanji: "子", hiragana: "こ", meaning: "아이, 자식", day: 5 },
  { id: 115, kanji: "公園", hiragana: "こうえん", meaning: "공원", day: 5 },
  { id: 116, kanji: "紅茶", hiragana: "こうちゃ", meaning: "홍차", day: 5 },
  { id: 117, kanji: "交番", hiragana: "こうばん", meaning: "파출소", day: 5 },
  { id: 118, kanji: "声", hiragana: "こえ", meaning: "목소리", day: 5 },
  { id: 119, kanji: "ここ", hiragana: "ここ", meaning: "여기, 이곳", day: 5 },
  { id: 120, kanji: "午後", hiragana: "ごご", meaning: "오후", day: 5 },
  { id: 121, kanji: "午前", hiragana: "ごぜん", meaning: "오전", day: 5 },
  { id: 122, kanji: "こちら", hiragana: "こちら", meaning: "이쪽, 이분", day: 5 },
  { id: 123, kanji: "今年", hiragana: "ことし", meaning: "올해", day: 5 },
  { id: 124, kanji: "子ども", hiragana: "こども", meaning: "아이, 어린이", day: 5 },
  { id: 125, kanji: "ご飯", hiragana: "ごはん", meaning: "밥, 식사", day: 5 },
  { id: 126, kanji: "これ", hiragana: "これ", meaning: "이것", day: 5 },
  { id: 127, kanji: "今月", hiragana: "こんげつ", meaning: "이번 달", day: 5 },
  { id: 128, kanji: "今週", hiragana: "こんしゅう", meaning: "이번 주", day: 5 },
  { id: 129, kanji: "今晩", hiragana: "こんばん", meaning: "오늘 밤", day: 5 },
  { id: 130, kanji: "最後", hiragana: "さいご", meaning: "마지막", day: 5 },
  { id: 131, kanji: "財布", hiragana: "さいふ", meaning: "지갑", day: 5 },
  { id: 132, kanji: "魚", hiragana: "さかな", meaning: "생선, 물고기", day: 5 },
  { id: 133, kanji: "先", hiragana: "さき", meaning: "앞, 먼저, 전", day: 5 },
  { id: 134, kanji: "作文", hiragana: "さくぶん", meaning: "작문, 글짓기", day: 5 },
  { id: 135, kanji: "散歩", hiragana: "さんぽ", meaning: "산책", day: 5 },
  { id: 136, kanji: "塩", hiragana: "しお", meaning: "소금", day: 5 },
  { id: 137, kanji: "時間", hiragana: "じかん", meaning: "시간", day: 5 },
  { id: 138, kanji: "仕事", hiragana: "しごと", meaning: "일, 직업", day: 5 },
  { id: 139, kanji: "辞書", hiragana: "じしょ", meaning: "사전", day: 5 },

  // ===== Day 6 =====
  { id: 140, kanji: "下", hiragana: "した", meaning: "아래, 밑", day: 6 },
  { id: 141, kanji: "写真", hiragana: "しゃしん", meaning: "사진", day: 6 },
  { id: 142, kanji: "宿題", hiragana: "しゅくだい", meaning: "숙제", day: 6 },
  { id: 143, kanji: "食堂", hiragana: "しょくどう", meaning: "식당", day: 6 },
  { id: 144, kanji: "新聞", hiragana: "しんぶん", meaning: "신문", day: 6 },
  { id: 145, kanji: "すし", hiragana: "すし", meaning: "초밥, 스시", day: 6 },
  { id: 146, kanji: "背", hiragana: "せ", meaning: "키, 등", day: 6 },
  { id: 147, kanji: "生徒", hiragana: "せいと", meaning: "학생 (초중고)", day: 6 },
  { id: 148, kanji: "せっけん", hiragana: "せっけん", meaning: "비누", day: 6 },
  { id: 149, kanji: "千", hiragana: "せん", meaning: "천 (1000)", day: 6 },
  { id: 150, kanji: "先月", hiragana: "せんげつ", meaning: "지난달", day: 6 },
  { id: 151, kanji: "先週", hiragana: "せんしゅう", meaning: "지난주", day: 6 },
  { id: 152, kanji: "先生", hiragana: "せんせい", meaning: "선생님", day: 6 },
  { id: 153, kanji: "そこ", hiragana: "そこ", meaning: "거기, 그곳", day: 6 },
  { id: 154, kanji: "そちら", hiragana: "そちら", meaning: "그쪽, 그분", day: 6 },
  { id: 155, kanji: "外", hiragana: "そと", meaning: "밖, 외부", day: 6 },
  { id: 156, kanji: "そば (麺)", hiragana: "そば", meaning: "소바 (메밀국수)", day: 6 },
  { id: 157, kanji: "そば (側)", hiragana: "そば", meaning: "옆, 곁", day: 6 },
  { id: 158, kanji: "空", hiragana: "そら", meaning: "하늘", day: 6 },
  { id: 159, kanji: "それ", hiragana: "それ", meaning: "그것", day: 6 },
  { id: 160, kanji: "大学", hiragana: "だいがく", meaning: "대학교", day: 6 },
  { id: 161, kanji: "台所", hiragana: "だいどころ", meaning: "부엌", day: 6 },
  { id: 162, kanji: "建物", hiragana: "たてもの", meaning: "건물", day: 6 },
  { id: 163, kanji: "たばこ", hiragana: "たばこ", meaning: "담배", day: 6 },
  { id: 164, kanji: "食べ物", hiragana: "たべもの", meaning: "음식, 먹을 것", day: 6 },
  { id: 165, kanji: "たまご", hiragana: "たまご", meaning: "달걀", day: 6 },
  { id: 166, kanji: "だれ", hiragana: "だれ", meaning: "누구", day: 6 },

  // ===== Day 7 =====
  { id: 167, kanji: "誕生日", hiragana: "たんじょうび", meaning: "생일", day: 7 },
  { id: 168, kanji: "地下鉄", hiragana: "ちかてつ", meaning: "지하철", day: 7 },
  { id: 169, kanji: "地図", hiragana: "ちず", meaning: "지도", day: 7 },
  { id: 170, kanji: "父", hiragana: "ちち", meaning: "(내) 아버지", day: 7 },
  { id: 171, kanji: "次", hiragana: "つぎ", meaning: "다음", day: 7 },
  { id: 172, kanji: "つくえ", hiragana: "つくえ", meaning: "책상", day: 7 },
  { id: 173, kanji: "作り方", hiragana: "つくりかた", meaning: "만드는 방법", day: 7 },
  { id: 174, kanji: "手", hiragana: "て", meaning: "손", day: 7 },
  { id: 175, kanji: "手紙", hiragana: "てがみ", meaning: "편지", day: 7 },
  { id: 176, kanji: "出口", hiragana: "でぐち", meaning: "출구", day: 7 },
  { id: 177, kanji: "天気", hiragana: "てんき", meaning: "날씨", day: 7 },
  { id: 178, kanji: "電気", hiragana: "でんき", meaning: "전기, 불", day: 7 },
  { id: 179, kanji: "電車", hiragana: "でんしゃ", meaning: "전철, 전차", day: 7 },
  { id: 180, kanji: "電話", hiragana: "でんわ", meaning: "전화", day: 7 },
  { id: 181, kanji: "動物", hiragana: "どうぶつ", meaning: "동물", day: 7 },
  { id: 182, kanji: "時計", hiragana: "とけい", meaning: "시계", day: 7 },
  { id: 183, kanji: "どこ", hiragana: "どこ", meaning: "어디, 어느 곳", day: 7 },
  { id: 184, kanji: "ところ", hiragana: "ところ", meaning: "곳, 장소", day: 7 },
  { id: 185, kanji: "年", hiragana: "とし", meaning: "나이, 해", day: 7 },
  { id: 186, kanji: "図書館", hiragana: "としょかん", meaning: "도서관", day: 7 },
  { id: 187, kanji: "どちら", hiragana: "どちら", meaning: "어느 쪽, 어디 (정중)", day: 7 },
  { id: 188, kanji: "どなた", hiragana: "どなた", meaning: "누구 (정중), 어느 분", day: 7 },
  { id: 189, kanji: "となり", hiragana: "となり", meaning: "이웃, 옆", day: 7 },
  { id: 190, kanji: "友だち", hiragana: "ともだち", meaning: "친구", day: 7 },
  { id: 191, kanji: "鳥", hiragana: "とり", meaning: "새", day: 7 },
  { id: 192, kanji: "鶏肉", hiragana: "とりにく", meaning: "닭고기", day: 7 },
  { id: 193, kanji: "どれ", hiragana: "どれ", meaning: "어느 것", day: 7 },

  // ===== Day 8 =====
  { id: 194, kanji: "中", hiragana: "なか", meaning: "안, 중간, 속", day: 8 },
  { id: 195, kanji: "夏", hiragana: "なつ", meaning: "여름", day: 8 },
  { id: 196, kanji: "夏休み", hiragana: "なつやすみ", meaning: "여름방학, 여름휴가", day: 8 },
  { id: 197, kanji: "何", hiragana: "なに", meaning: "무엇, 몇", day: 8 },
  { id: 198, kanji: "名前", hiragana: "なまえ", meaning: "이름", day: 8 },
  { id: 199, kanji: "肉", hiragana: "にく", meaning: "고기", day: 8 },
  { id: 200, kanji: "西", hiragana: "にし", meaning: "서쪽", day: 8 },
  { id: 201, kanji: "日本語", hiragana: "にほんご", meaning: "일본어", day: 8 },
  { id: 202, kanji: "日本人", hiragana: "にほんじん", meaning: "일본인", day: 8 },
  { id: 203, kanji: "庭", hiragana: "にわ", meaning: "정원, 마당", day: 8 },
  { id: 204, kanji: "猫", hiragana: "ねこ", meaning: "고양이", day: 8 },
  { id: 205, kanji: "飲み物", hiragana: "のみもの", meaning: "음료", day: 8 },
  { id: 206, kanji: "灰皿", hiragana: "はいざら", meaning: "재떨이", day: 8 },
  { id: 207, kanji: "葉書", hiragana: "はがき", meaning: "엽서", day: 8 },
  { id: 208, kanji: "二十歳", hiragana: "はたち", meaning: "스무 살, 20세", day: 8 },
  { id: 209, kanji: "鼻", hiragana: "はな", meaning: "코", day: 8 },
  { id: 210, kanji: "花", hiragana: "はな", meaning: "꽃", day: 8 },
  { id: 211, kanji: "話", hiragana: "はなし", meaning: "이야기", day: 8 },
  { id: 212, kanji: "母", hiragana: "はは", meaning: "(내) 어머니", day: 8 },
  { id: 213, kanji: "春", hiragana: "はる", meaning: "봄", day: 8 },
  { id: 214, kanji: "番号", hiragana: "ばんごう", meaning: "번호", day: 8 },
  { id: 215, kanji: "晩ご飯", hiragana: "ばんごはん", meaning: "저녁밥, 저녁 식사", day: 8 },
  { id: 216, kanji: "半分", hiragana: "はんぶん", meaning: "절반", day: 8 },
  { id: 217, kanji: "東", hiragana: "ひがし", meaning: "동쪽", day: 8 },
  { id: 218, kanji: "飛行機", hiragana: "ひこうき", meaning: "비행기", day: 8 },
  { id: 219, kanji: "人", hiragana: "ひと", meaning: "사람", day: 8 },
  { id: 220, kanji: "百", hiragana: "ひゃく", meaning: "백 (100)", day: 8 },
  { id: 221, kanji: "百点", hiragana: "ひゃくてん", meaning: "백 점 (100점)", day: 8 },

  // ===== Day 9 =====
  { id: 222, kanji: "病院", hiragana: "びょういん", meaning: "병원", day: 9 },
  { id: 223, kanji: "病気", hiragana: "びょうき", meaning: "병, 질병", day: 9 },
  { id: 224, kanji: "ひらがな", hiragana: "ひらがな", meaning: "히라가나", day: 9 },
  { id: 225, kanji: "昼", hiragana: "ひる", meaning: "낮, 점심", day: 9 },
  { id: 226, kanji: "昼ご飯", hiragana: "ひるごはん", meaning: "점심밥, 점심 식사", day: 9 },
  { id: 227, kanji: "服", hiragana: "ふく", meaning: "옷", day: 9 },
  { id: 228, kanji: "冬", hiragana: "ふゆ", meaning: "겨울", day: 9 },
  { id: 229, kanji: "部屋", hiragana: "へや", meaning: "방", day: 9 },
  { id: 230, kanji: "勉強", hiragana: "べんきょう", meaning: "공부", day: 9 },
  { id: 231, kanji: "方", hiragana: "かた", meaning: "분 (사람), 쪽, 방법", day: 9 },
  { id: 232, kanji: "帽子", hiragana: "ぼうし", meaning: "모자", day: 9 },
  { id: 233, kanji: "ほか", hiragana: "ほか", meaning: "그 외, 다른", day: 9 },
  { id: 234, kanji: "本", hiragana: "ほん", meaning: "책", day: 9 },
  { id: 235, kanji: "毎朝", hiragana: "まいあさ", meaning: "매일 아침", day: 9 },
  { id: 236, kanji: "毎月", hiragana: "まいつき", meaning: "매달", day: 9 },
  { id: 237, kanji: "毎週", hiragana: "まいしゅう", meaning: "매주", day: 9 },
  { id: 238, kanji: "毎日", hiragana: "まいにち", meaning: "매일", day: 9 },
  { id: 239, kanji: "毎年", hiragana: "まいとし", meaning: "매년", day: 9 },
  { id: 240, kanji: "毎晩", hiragana: "まいばん", meaning: "매일 밤", day: 9 },
  { id: 241, kanji: "前", hiragana: "まえ", meaning: "앞, 이전", day: 9 },
  { id: 242, kanji: "町", hiragana: "まち", meaning: "마을, 동네", day: 9 },
  { id: 243, kanji: "窓", hiragana: "まど", meaning: "창문", day: 9 },
  { id: 244, kanji: "右", hiragana: "みぎ", meaning: "오른쪽", day: 9 },
  { id: 245, kanji: "水", hiragana: "みず", meaning: "물", day: 9 },
  { id: 246, kanji: "店", hiragana: "みせ", meaning: "가게", day: 9 },
  { id: 247, kanji: "道", hiragana: "みち", meaning: "길", day: 9 },
  { id: 248, kanji: "みなさん", hiragana: "みなさん", meaning: "여러분", day: 9 },
  { id: 249, kanji: "南", hiragana: "みなみ", meaning: "남쪽", day: 9 },

  // ===== Day 10 =====
  { id: 250, kanji: "耳", hiragana: "みみ", meaning: "귀", day: 10 },
  { id: 251, kanji: "みんな", hiragana: "みんな", meaning: "모두, 다", day: 10 },
  { id: 252, kanji: "昔", hiragana: "むかし", meaning: "옛날", day: 10 },
  { id: 253, kanji: "息子", hiragana: "むすこ", meaning: "(내) 아들", day: 10 },
  { id: 254, kanji: "目", hiragana: "め", meaning: "눈", day: 10 },
  { id: 255, kanji: "めがね", hiragana: "めがね", meaning: "안경", day: 10 },
  { id: 256, kanji: "物", hiragana: "もの", meaning: "물건, 것", day: 10 },
  { id: 257, kanji: "門", hiragana: "もん", meaning: "문, 대문", day: 10 },
  { id: 258, kanji: "問題", hiragana: "もんだい", meaning: "문제", day: 10 },
  { id: 259, kanji: "八百屋", hiragana: "やおや", meaning: "채소 가게, 야채 가게", day: 10 },
  { id: 260, kanji: "野菜", hiragana: "やさい", meaning: "채소, 야채", day: 10 },
  { id: 261, kanji: "休み", hiragana: "やすみ", meaning: "쉬는 날, 휴가", day: 10 },
  { id: 262, kanji: "山", hiragana: "やま", meaning: "산", day: 10 },
  { id: 263, kanji: "夕方", hiragana: "ゆうがた", meaning: "저녁 무렵, 황혼", day: 10 },
  { id: 264, kanji: "夕飯", hiragana: "ゆうはん", meaning: "저녁밥", day: 10 },
  { id: 265, kanji: "雪", hiragana: "ゆき", meaning: "눈 (설)", day: 10 },
  { id: 266, kanji: "洋服", hiragana: "ようふく", meaning: "양복, 서양식 옷", day: 10 },
  { id: 267, kanji: "横", hiragana: "よこ", meaning: "옆, 가로", day: 10 },
  { id: 268, kanji: "夜", hiragana: "よる", meaning: "밤", day: 10 },
  { id: 269, kanji: "来月", hiragana: "らいげつ", meaning: "다음 달", day: 10 },
  { id: 270, kanji: "来週", hiragana: "らいしゅう", meaning: "다음 주", day: 10 },
  { id: 271, kanji: "来年", hiragana: "らいねん", meaning: "내년", day: 10 },
  { id: 272, kanji: "留学生", hiragana: "りゅうがくせい", meaning: "유학생", day: 10 },
  { id: 273, kanji: "料理", hiragana: "りょうり", meaning: "요리", day: 10 },
  { id: 274, kanji: "練習", hiragana: "れんしゅう", meaning: "연습", day: 10 },
  { id: 275, kanji: "私", hiragana: "わたし", meaning: "나, 저", day: 10 },

  // ===== Day 11 - Numbers / 수 =====
  { id: 276, kanji: "一", hiragana: "いち", meaning: "일, 1", day: 11 },
  { id: 277, kanji: "二", hiragana: "に", meaning: "이, 2", day: 11 },
  { id: 278, kanji: "三", hiragana: "さん", meaning: "삼, 3", day: 11 },
  { id: 279, kanji: "四", hiragana: "し / よん", meaning: "사, 4", day: 11 },
  { id: 280, kanji: "五", hiragana: "ご", meaning: "오, 5", day: 11 },
  { id: 281, kanji: "六", hiragana: "ろく", meaning: "육, 6", day: 11 },
  { id: 282, kanji: "七", hiragana: "しち / なな", meaning: "칠, 7", day: 11 },
  { id: 283, kanji: "八", hiragana: "はち", meaning: "팔, 8", day: 11 },
  { id: 284, kanji: "九", hiragana: "く / きゅう", meaning: "구, 9", day: 11 },
  { id: 285, kanji: "十", hiragana: "じゅう", meaning: "십, 10", day: 11 },
  { id: 286, kanji: "一つ", hiragana: "ひとつ", meaning: "하나, 한 개", day: 11 },
  { id: 287, kanji: "二つ", hiragana: "ふたつ", meaning: "둘, 두 개", day: 11 },
  { id: 288, kanji: "三つ", hiragana: "みっつ", meaning: "셋, 세 개", day: 11 },
  { id: 289, kanji: "四つ", hiragana: "よっつ", meaning: "넷, 네 개", day: 11 },
  { id: 290, kanji: "五つ", hiragana: "いつつ", meaning: "다섯, 다섯 개", day: 11 },
  { id: 291, kanji: "六つ", hiragana: "むっつ", meaning: "여섯, 여섯 개", day: 11 },
  { id: 292, kanji: "七つ", hiragana: "ななつ", meaning: "일곱, 일곱 개", day: 11 },
  { id: 293, kanji: "八つ", hiragana: "やっつ", meaning: "여덟, 여덟 개", day: 11 },
  { id: 294, kanji: "九つ", hiragana: "ここのつ", meaning: "아홉, 아홉 개", day: 11 },

  // ===== Day 12 - Counters (층/번/회) =====
  { id: 295, kanji: "〜階", hiragana: "〜かい", meaning: "〜층", day: 12 },
  { id: 296, kanji: "〜回", hiragana: "〜かい", meaning: "〜번, 〜회 (횟수)", day: 12 },
  { id: 297, kanji: "〜番", hiragana: "〜ばん", meaning: "〜번 (번호)", day: 12 },

  // ===== Day 13 - Counters (엔/년/월) =====
  { id: 298, kanji: "〜円", hiragana: "〜えん", meaning: "〜엔 (금액)", day: 13 },
  { id: 299, kanji: "〜年", hiragana: "〜ねん", meaning: "〜년 (연도)", day: 13 },
  { id: 300, kanji: "〜月", hiragana: "〜がつ", meaning: "〜월 (달)", day: 13 },
  { id: 301, kanji: "一月", hiragana: "いちがつ", meaning: "1월, 일월", day: 13 },
  { id: 302, kanji: "二月", hiragana: "にがつ", meaning: "2월, 이월", day: 13 },
  { id: 303, kanji: "三月", hiragana: "さんがつ", meaning: "3월, 삼월", day: 13 },
  { id: 304, kanji: "四月", hiragana: "しがつ", meaning: "4월, 사월", day: 13 },
  { id: 305, kanji: "五月", hiragana: "ごがつ", meaning: "5월, 오월", day: 13 },
  { id: 306, kanji: "六月", hiragana: "ろくがつ", meaning: "6월, 유월", day: 13 },
  { id: 307, kanji: "七月", hiragana: "しちがつ", meaning: "7월, 칠월", day: 13 },
  { id: 308, kanji: "八月", hiragana: "はちがつ", meaning: "8월, 팔월", day: 13 },
  { id: 309, kanji: "九月", hiragana: "くがつ", meaning: "9월, 구월", day: 13 },
  { id: 310, kanji: "十月", hiragana: "じゅうがつ", meaning: "10월, 시월", day: 13 },
  { id: 311, kanji: "十一月", hiragana: "じゅういちがつ", meaning: "11월, 십일월", day: 13 },
  { id: 312, kanji: "十二月", hiragana: "じゅうにがつ", meaning: "12월, 십이월", day: 13 },

  // ===== Day 14 - Counters (일/시) =====
  { id: 313, kanji: "〜日", hiragana: "〜にち / 〜か", meaning: "〜일 (날짜)", day: 14 },
  { id: 314, kanji: "〜時", hiragana: "〜じ", meaning: "〜시 (시각)", day: 14 },

  // ===== Day 15 - Counters (분/요일/잔) =====
  { id: 315, kanji: "〜分", hiragana: "〜ふん / 〜ぷん", meaning: "〜분 (시간)", day: 15 },
  { id: 316, kanji: "月曜日", hiragana: "げつようび", meaning: "월요일", day: 15 },
  { id: 317, kanji: "火曜日", hiragana: "かようび", meaning: "화요일", day: 15 },
  { id: 318, kanji: "水曜日", hiragana: "すいようび", meaning: "수요일", day: 15 },
  { id: 319, kanji: "木曜日", hiragana: "もくようび", meaning: "목요일", day: 15 },
  { id: 320, kanji: "金曜日", hiragana: "きんようび", meaning: "금요일", day: 15 },
  { id: 321, kanji: "土曜日", hiragana: "どようび", meaning: "토요일", day: 15 },
  { id: 322, kanji: "日曜日", hiragana: "にちようび", meaning: "일요일", day: 15 },
  { id: 323, kanji: "〜杯", hiragana: "〜はい", meaning: "〜잔 (컵/잔 세는 단위)", day: 15 },

  // ===== Day 16 - Counters (배/자루/장) =====
  { id: 324, kanji: "〜倍", hiragana: "〜ばい", meaning: "〜배 (倍)", day: 16 },
  { id: 325, kanji: "〜本", hiragana: "〜ほん", meaning: "〜자루, 〜병 (기다란 것)", day: 16 },
  { id: 326, kanji: "〜枚", hiragana: "〜まい", meaning: "〜장, 〜매 (얇은 것)", day: 16 },

  // ===== Day 17 - Counters (명/마리) =====
  { id: 327, kanji: "〜人", hiragana: "〜にん", meaning: "〜명, 〜사람", day: 17 },
  { id: 328, kanji: "〜匹", hiragana: "〜ひき", meaning: "〜마리 (작은 동물)", day: 17 },

  // ===== Day 18 - Verbs (동사) =====
  { id: 329, kanji: "会う", hiragana: "あう", meaning: "만나다", day: 18 },
  { id: 330, kanji: "上がる", hiragana: "あがる", meaning: "오르다, 올라가다", day: 18 },
  { id: 331, kanji: "開く", hiragana: "あく", meaning: "열리다", day: 18 },
  { id: 332, kanji: "開ける", hiragana: "あける", meaning: "열다", day: 18 },
  { id: 333, kanji: "あげる", hiragana: "あげる", meaning: "주다, 올리다", day: 18 },
  { id: 334, kanji: "上げる", hiragana: "あげる", meaning: "올리다", day: 18 },
  { id: 335, kanji: "遊ぶ", hiragana: "あそぶ", meaning: "놀다", day: 18 },
  { id: 336, kanji: "あびる", hiragana: "あびる", meaning: "뒤집어 쓰다, 샤워하다", day: 18 },
  { id: 337, kanji: "洗う", hiragana: "あらう", meaning: "씻다", day: 18 },
  { id: 338, kanji: "ある", hiragana: "ある", meaning: "있다 (사물)", day: 18 },
  { id: 339, kanji: "歩く", hiragana: "あるく", meaning: "걷다", day: 18 },
  { id: 340, kanji: "言う", hiragana: "いう", meaning: "말하다", day: 18 },
  { id: 341, kanji: "行く", hiragana: "いく", meaning: "가다", day: 18 },
  { id: 342, kanji: "いる", hiragana: "いる", meaning: "있다 (사람/동물)", day: 18 },
  { id: 343, kanji: "要る", hiragana: "いる", meaning: "필요하다", day: 18 },
  { id: 344, kanji: "入れる", hiragana: "いれる", meaning: "넣다", day: 18 },
  { id: 345, kanji: "歌う", hiragana: "うたう", meaning: "노래하다", day: 18 },
  { id: 346, kanji: "生まれる", hiragana: "うまれる", meaning: "태어나다", day: 18 },
  { id: 347, kanji: "売る", hiragana: "うる", meaning: "팔다", day: 18 },
  { id: 348, kanji: "起きる", hiragana: "おきる", meaning: "일어나다", day: 18 },
  { id: 349, kanji: "置く", hiragana: "おく", meaning: "놓다, 두다", day: 18 },
  { id: 350, kanji: "教える", hiragana: "おしえる", meaning: "가르치다, 알려주다", day: 18 },
  { id: 351, kanji: "押す", hiragana: "おす", meaning: "밀다, 누르다", day: 18 },
  { id: 352, kanji: "泳ぐ", hiragana: "およぐ", meaning: "수영하다", day: 18 },
  { id: 353, kanji: "終わる", hiragana: "おわる", meaning: "끝나다", day: 18 },
  { id: 354, kanji: "買う", hiragana: "かう", meaning: "사다", day: 18 },
  { id: 355, kanji: "帰る", hiragana: "かえる", meaning: "돌아가다, 귀가하다", day: 18 },

  // ===== Day 19 - Verbs =====
  { id: 356, kanji: "かかる", hiragana: "かかる", meaning: "걸리다 (시간/비용)", day: 19 },
  { id: 357, kanji: "書く", hiragana: "かく", meaning: "쓰다", day: 19 },
  { id: 358, kanji: "かぶる", hiragana: "かぶる", meaning: "쓰다 (모자 등)", day: 19 },
  { id: 359, kanji: "消える", hiragana: "きえる", meaning: "꺼지다, 사라지다", day: 19 },
  { id: 360, kanji: "聞く", hiragana: "きく", meaning: "듣다, 묻다", day: 19 },
  { id: 361, kanji: "切る", hiragana: "きる", meaning: "자르다", day: 19 },
  { id: 362, kanji: "着る", hiragana: "きる", meaning: "입다 (옷)", day: 19 },
  { id: 363, kanji: "来る", hiragana: "くる", meaning: "오다", day: 19 },
  { id: 364, kanji: "答える", hiragana: "こたえる", meaning: "대답하다", day: 19 },
  { id: 365, kanji: "咲く", hiragana: "さく", meaning: "피다 (꽃)", day: 19 },
  { id: 366, kanji: "死ぬ", hiragana: "しぬ", meaning: "죽다", day: 19 },
  { id: 367, kanji: "閉まる", hiragana: "しまる", meaning: "닫히다", day: 19 },
  { id: 368, kanji: "閉める", hiragana: "しめる", meaning: "닫다", day: 19 },
  { id: 369, kanji: "住む", hiragana: "すむ", meaning: "살다, 거주하다", day: 19 },
  { id: 370, kanji: "する", hiragana: "する", meaning: "하다", day: 19 },
  { id: 371, kanji: "座る", hiragana: "すわる", meaning: "앉다", day: 19 },
  { id: 372, kanji: "出す", hiragana: "だす", meaning: "내다, 꺼내다", day: 19 },
  { id: 373, kanji: "立つ", hiragana: "たつ", meaning: "서다", day: 19 },
  { id: 374, kanji: "食べる", hiragana: "たべる", meaning: "먹다", day: 19 },
  { id: 375, kanji: "使う", hiragana: "つかう", meaning: "사용하다, 쓰다", day: 19 },
  { id: 376, kanji: "作る", hiragana: "つくる", meaning: "만들다", day: 19 },
  { id: 377, kanji: "つける", hiragana: "つける", meaning: "켜다, 붙이다", day: 19 },
  { id: 378, kanji: "出かける", hiragana: "でかける", meaning: "외출하다", day: 19 },
  { id: 379, kanji: "出る", hiragana: "でる", meaning: "나오다, 나가다", day: 19 },
  { id: 380, kanji: "飛ぶ", hiragana: "とぶ", meaning: "날다", day: 19 },
  { id: 381, kanji: "撮る", hiragana: "とる", meaning: "찍다 (사진)", day: 19 },
  { id: 382, kanji: "習う", hiragana: "ならう", meaning: "배우다", day: 19 },
  { id: 383, kanji: "並べる", hiragana: "ならべる", meaning: "늘어놓다, 나열하다", day: 19 },

  // ===== Day 20 - Verbs =====
  { id: 384, kanji: "寝る", hiragana: "ねる", meaning: "자다", day: 20 },
  { id: 385, kanji: "登る", hiragana: "のぼる", meaning: "오르다, 올라가다", day: 20 },
  { id: 386, kanji: "飲む", hiragana: "のむ", meaning: "마시다", day: 20 },
  { id: 387, kanji: "乗る", hiragana: "のる", meaning: "타다", day: 20 },
  { id: 388, kanji: "入る", hiragana: "はいる", meaning: "들어가다", day: 20 },
  { id: 389, kanji: "始まる", hiragana: "はじまる", meaning: "시작되다", day: 20 },
  { id: 390, kanji: "話す", hiragana: "はなす", meaning: "말하다, 이야기하다", day: 20 },
  { id: 391, kanji: "はる", hiragana: "はる", meaning: "붙이다", day: 20 },
  { id: 392, kanji: "弾く", hiragana: "ひく", meaning: "연주하다 (악기)", day: 20 },
  { id: 393, kanji: "降る", hiragana: "ふる", meaning: "내리다 (비/눈)", day: 20 },
  { id: 394, kanji: "曲がる", hiragana: "まがる", meaning: "굽다, 돌다", day: 20 },
  { id: 395, kanji: "待つ", hiragana: "まつ", meaning: "기다리다", day: 20 },
  { id: 396, kanji: "磨く", hiragana: "みがく", meaning: "닦다", day: 20 },
  { id: 397, kanji: "見せる", hiragana: "みせる", meaning: "보여주다", day: 20 },
  { id: 398, kanji: "見る", hiragana: "みる", meaning: "보다", day: 20 },
  { id: 399, kanji: "持つ", hiragana: "もつ", meaning: "가지다, 들다", day: 20 },
  { id: 400, kanji: "もらう", hiragana: "もらう", meaning: "받다", day: 20 },
  { id: 401, kanji: "休む", hiragana: "やすむ", meaning: "쉬다, 결석하다", day: 20 },
  { id: 402, kanji: "呼ぶ", hiragana: "よぶ", meaning: "부르다", day: 20 },
  { id: 403, kanji: "読む", hiragana: "よむ", meaning: "읽다", day: 20 },
  { id: 404, kanji: "分かる", hiragana: "わかる", meaning: "알다, 이해하다", day: 20 },

  // ===== Day 21 - い形容詞 (i-adjectives) =====
  { id: 405, kanji: "青い", hiragana: "あおい", meaning: "파랗다, 파란", day: 21 },
  { id: 406, kanji: "赤い", hiragana: "あかい", meaning: "빨갛다, 빨간", day: 21 },
  { id: 407, kanji: "明るい", hiragana: "あかるい", meaning: "밝다, 밝은", day: 21 },
  { id: 408, kanji: "暖かい", hiragana: "あたたかい", meaning: "따뜻하다, 따뜻한", day: 21 },
  { id: 409, kanji: "新しい", hiragana: "あたらしい", meaning: "새롭다, 새", day: 21 },
  { id: 410, kanji: "暑い", hiragana: "あつい", meaning: "덥다, 더운", day: 21 },
  { id: 411, kanji: "危ない", hiragana: "あぶない", meaning: "위험하다, 위험한", day: 21 },
  { id: 412, kanji: "甘い", hiragana: "あまい", meaning: "달다, 달콤한", day: 21 },
  { id: 413, kanji: "いい / よい", hiragana: "いい / よい", meaning: "좋다, 좋은", day: 21 },
  { id: 414, kanji: "忙しい", hiragana: "いそがしい", meaning: "바쁘다, 바쁜", day: 21 },
  { id: 415, kanji: "痛い", hiragana: "いたい", meaning: "아프다, 아픈", day: 21 },
  { id: 416, kanji: "うるさい", hiragana: "うるさい", meaning: "시끄럽다, 귀찮다", day: 21 },
  { id: 417, kanji: "おいしい", hiragana: "おいしい", meaning: "맛있다, 맛있는", day: 21 },
  { id: 418, kanji: "多い", hiragana: "おおい", meaning: "많다, 많은", day: 21 },
  { id: 419, kanji: "大きい", hiragana: "おおきい", meaning: "크다, 큰", day: 21 },
  { id: 420, kanji: "重い", hiragana: "おもい", meaning: "무겁다, 무거운", day: 21 },
  { id: 421, kanji: "おもしろい", hiragana: "おもしろい", meaning: "재미있다, 흥미롭다", day: 21 },
  { id: 422, kanji: "軽い", hiragana: "かるい", meaning: "가볍다, 가벼운", day: 21 },
  { id: 423, kanji: "かわいい", hiragana: "かわいい", meaning: "귀엽다, 예쁘다", day: 21 },
  { id: 424, kanji: "黄色い", hiragana: "きいろい", meaning: "노랗다, 노란", day: 21 },
  { id: 425, kanji: "暗い", hiragana: "くらい", meaning: "어둡다, 어두운", day: 21 },
  { id: 426, kanji: "黒い", hiragana: "くろい", meaning: "검다, 검은", day: 21 },
  { id: 427, kanji: "寒い", hiragana: "さむい", meaning: "춥다, 추운", day: 21 },
  { id: 428, kanji: "白い", hiragana: "しろい", meaning: "하얗다, 하얀", day: 21 },
  { id: 429, kanji: "少ない", hiragana: "すくない", meaning: "적다, 적은", day: 21 },
  { id: 430, kanji: "狭い", hiragana: "せまい", meaning: "좁다, 좁은", day: 21 },

  // ===== Day 22 - い形容詞 continued =====
  { id: 431, kanji: "高い", hiragana: "たかい", meaning: "높다, 비싸다", day: 22 },
  { id: 432, kanji: "楽しい", hiragana: "たのしい", meaning: "즐겁다, 재미있다", day: 22 },
  { id: 433, kanji: "小さい", hiragana: "ちいさい", meaning: "작다, 작은", day: 22 },
  { id: 434, kanji: "近い", hiragana: "ちかい", meaning: "가깝다, 가까운", day: 22 },
  { id: 435, kanji: "強い", hiragana: "つよい", meaning: "강하다, 강한", day: 22 },
  { id: 436, kanji: "遠い", hiragana: "とおい", meaning: "멀다, 먼", day: 22 },
  { id: 437, kanji: "ない", hiragana: "ない", meaning: "없다", day: 22 },
  { id: 438, kanji: "長い", hiragana: "ながい", meaning: "길다, 긴", day: 22 },
  { id: 439, kanji: "速い / 早い", hiragana: "はやい", meaning: "빠르다, 이르다", day: 22 },
  { id: 440, kanji: "低い", hiragana: "ひくい", meaning: "낮다, 낮은", day: 22 },
  { id: 441, kanji: "広い", hiragana: "ひろい", meaning: "넓다, 넓은", day: 22 },
  { id: 442, kanji: "古い", hiragana: "ふるい", meaning: "오래되다, 낡다", day: 22 },
  { id: 443, kanji: "まずい", hiragana: "まずい", meaning: "맛없다, 좋지 않다", day: 22 },
  { id: 444, kanji: "短い", hiragana: "みじかい", meaning: "짧다, 짧은", day: 22 },
  { id: 445, kanji: "難しい", hiragana: "むずかしい", meaning: "어렵다, 어려운", day: 22 },
  { id: 446, kanji: "安い", hiragana: "やすい", meaning: "싸다, 저렴하다", day: 22 },
  { id: 447, kanji: "弱い", hiragana: "よわい", meaning: "약하다, 약한", day: 22 },
  { id: 448, kanji: "悪い", hiragana: "わるい", meaning: "나쁘다, 나쁜", day: 22 },

  // ===== Day 23 - な形容詞 (na-adjectives) =====
  { id: 449, kanji: "あんな", hiragana: "あんな", meaning: "저런", day: 23 },
  { id: 450, kanji: "いやな", hiragana: "いやな", meaning: "싫다, 싫은", day: 23 },
  { id: 451, kanji: "いろいろな", hiragana: "いろいろな", meaning: "여러 가지, 다양한", day: 23 },
  { id: 452, kanji: "大きな", hiragana: "おおきな", meaning: "큰 (な형)", day: 23 },
  { id: 453, kanji: "同じな", hiragana: "おなじ", meaning: "같다, 같은", day: 23 },
  { id: 454, kanji: "簡単な", hiragana: "かんたんな", meaning: "간단하다, 쉽다", day: 23 },
  { id: 455, kanji: "きらいな", hiragana: "きらいな", meaning: "싫어하다, 싫은", day: 23 },
  { id: 456, kanji: "きれいな", hiragana: "きれいな", meaning: "예쁘다, 깨끗하다", day: 23 },
  { id: 457, kanji: "元気な", hiragana: "げんきな", meaning: "건강하다, 활기차다", day: 23 },
  { id: 458, kanji: "こんな", hiragana: "こんな", meaning: "이런", day: 23 },
  { id: 459, kanji: "静かな", hiragana: "しずかな", meaning: "조용하다, 조용한", day: 23 },
  { id: 460, kanji: "上手な", hiragana: "じょうずな", meaning: "잘하다, 능숙하다", day: 23 },
  { id: 461, kanji: "丈夫な", hiragana: "じょうぶな", meaning: "튼튼하다, 건강하다", day: 23 },
  { id: 462, kanji: "好きな", hiragana: "すきな", meaning: "좋아하다, 좋아하는", day: 23 },
  { id: 463, kanji: "そんな", hiragana: "そんな", meaning: "그런", day: 23 },
  { id: 464, kanji: "大丈夫な", hiragana: "だいじょうぶな", meaning: "괜찮다, 안전하다", day: 23 },
  { id: 465, kanji: "大好きな", hiragana: "だいすきな", meaning: "매우 좋아하다", day: 23 },
  { id: 466, kanji: "大変な", hiragana: "たいへんな", meaning: "힘들다, 큰일이다", day: 23 },
  { id: 467, kanji: "小さな", hiragana: "ちいさな", meaning: "작은 (な형)", day: 23 },
  { id: 468, kanji: "どんな", hiragana: "どんな", meaning: "어떤", day: 23 },
  { id: 469, kanji: "にぎやかな", hiragana: "にぎやかな", meaning: "활기차다, 번화하다", day: 23 },
  { id: 470, kanji: "ひまな", hiragana: "ひまな", meaning: "한가하다, 심심하다", day: 23 },
  { id: 471, kanji: "便利な", hiragana: "べんりな", meaning: "편리하다, 편리한", day: 23 },
  { id: 472, kanji: "有名な", hiragana: "ゆうめいな", meaning: "유명하다, 유명한", day: 23 },

  // ===== Day 24 - Adverbs / 副詞 =====
  { id: 473, kanji: "あまり", hiragana: "あまり", meaning: "별로 (부정), 너무", day: 24 },
  { id: 474, kanji: "一番", hiragana: "いちばん", meaning: "가장, 제일", day: 24 },
  { id: 475, kanji: "いつ", hiragana: "いつ", meaning: "언제", day: 24 },
  { id: 476, kanji: "いっしょに", hiragana: "いっしょに", meaning: "함께, 같이", day: 24 },
  { id: 477, kanji: "いつも", hiragana: "いつも", meaning: "항상, 언제나", day: 24 },
  { id: 478, kanji: "おおぜい", hiragana: "おおぜい", meaning: "많은 사람들", day: 24 },
  { id: 479, kanji: "すぐ", hiragana: "すぐ", meaning: "곧, 바로", day: 24 },
  { id: 480, kanji: "少し", hiragana: "すこし", meaning: "조금, 약간", day: 24 },
  { id: 481, kanji: "全部", hiragana: "ぜんぶ", meaning: "전부, 모두", day: 24 },
  { id: 482, kanji: "たいへん", hiragana: "たいへん", meaning: "매우, 대단히", day: 24 },
  { id: 483, kanji: "たくさん", hiragana: "たくさん", meaning: "많이, 많은", day: 24 },
  { id: 484, kanji: "だんだん", hiragana: "だんだん", meaning: "점점, 차츰", day: 24 },
  { id: 485, kanji: "ちょっと", hiragana: "ちょっと", meaning: "조금, 잠깐", day: 24 },
  { id: 486, kanji: "どう", hiragana: "どう", meaning: "어떻게, 어떠한", day: 24 },
  { id: 487, kanji: "どうして", hiragana: "どうして", meaning: "왜, 어째서", day: 24 },
  { id: 488, kanji: "どうも", hiragana: "どうも", meaning: "어쩐지, 감사합니다 (간략)", day: 24 },
  { id: 489, kanji: "時々", hiragana: "ときどき", meaning: "때때로, 가끔", day: 24 },
  { id: 490, kanji: "とても", hiragana: "とても", meaning: "매우, 아주", day: 24 },
  { id: 491, kanji: "なぜ", hiragana: "なぜ", meaning: "왜, 어째서", day: 24 },
  { id: 492, kanji: "また", hiragana: "また", meaning: "또, 다시", day: 24 },
  { id: 493, kanji: "まだ", hiragana: "まだ", meaning: "아직", day: 24 },
  { id: 494, kanji: "まっすぐ", hiragana: "まっすぐ", meaning: "똑바로, 일직선으로", day: 24 },
  { id: 495, kanji: "もう一度", hiragana: "もういちど", meaning: "한 번 더", day: 24 },
  { id: 496, kanji: "もっと", hiragana: "もっと", meaning: "더, 더욱", day: 24 },
  { id: 497, kanji: "ゆっくり", hiragana: "ゆっくり", meaning: "천천히, 느긋하게", day: 24 },

  // ===== Day 25 - Demonstratives / Particles =====
  { id: 498, kanji: "あの", hiragana: "あの", meaning: "저 (저것의)", day: 25 },
  { id: 499, kanji: "この", hiragana: "この", meaning: "이 (이것의)", day: 25 },
  { id: 500, kanji: "その", hiragana: "その", meaning: "그 (그것의)", day: 25 },
  { id: 501, kanji: "どの", hiragana: "どの", meaning: "어느, 어느 것의", day: 25 },
  { id: 502, kanji: "でも", hiragana: "でも", meaning: "하지만, 그래도", day: 25 },
  { id: 503, kanji: "〜くらい / 〜ぐらい", hiragana: "〜くらい", meaning: "〜쯤, 〜정도", day: 25 },
  { id: 504, kanji: "〜ずつ", hiragana: "〜ずつ", meaning: "〜씩 (각각)", day: 25 },
  { id: 505, kanji: "〜だけ", hiragana: "〜だけ", meaning: "〜만, 〜뿐", day: 25 },

  // ===== Day 26 - Katakana words =====
  { id: 506, kanji: "アパート", hiragana: "アパート", meaning: "아파트", day: 26 },
  { id: 507, kanji: "エレベーター", hiragana: "エレベーター", meaning: "엘리베이터", day: 26 },
  { id: 508, kanji: "カップ", hiragana: "カップ", meaning: "컵 (손잡이 있는)", day: 26 },
  { id: 509, kanji: "カメラ", hiragana: "カメラ", meaning: "카메라", day: 26 },
  { id: 510, kanji: "カレンダー", hiragana: "カレンダー", meaning: "달력", day: 26 },
  { id: 511, kanji: "ギター", hiragana: "ギター", meaning: "기타", day: 26 },
  { id: 512, kanji: "クラス", hiragana: "クラス", meaning: "클래스, 반", day: 26 },
  { id: 513, kanji: "グラス", hiragana: "グラス", meaning: "유리잔", day: 26 },
  { id: 514, kanji: "コート", hiragana: "コート", meaning: "코트", day: 26 },
  { id: 515, kanji: "コーヒー", hiragana: "コーヒー", meaning: "커피", day: 26 },
  { id: 516, kanji: "コップ", hiragana: "コップ", meaning: "컵 (손잡이 없는)", day: 26 },
  { id: 517, kanji: "コピー", hiragana: "コピー", meaning: "복사", day: 26 },
  { id: 518, kanji: "シャツ", hiragana: "シャツ", meaning: "셔츠", day: 26 },
  { id: 519, kanji: "シャワー", hiragana: "シャワー", meaning: "샤워", day: 26 },
  { id: 520, kanji: "スカート", hiragana: "スカート", meaning: "스커트", day: 26 },
  { id: 521, kanji: "ストーブ", hiragana: "ストーブ", meaning: "난로", day: 26 },
  { id: 522, kanji: "スプーン", hiragana: "スプーン", meaning: "숟가락", day: 26 },
  { id: 523, kanji: "スポーツ", hiragana: "スポーツ", meaning: "스포츠", day: 26 },
  { id: 524, kanji: "ズボン", hiragana: "ズボン", meaning: "바지", day: 26 },
  { id: 525, kanji: "セーター", hiragana: "セーター", meaning: "스웨터", day: 26 },
  { id: 526, kanji: "ゼロ", hiragana: "ゼロ", meaning: "영, 0", day: 26 },
  { id: 527, kanji: "タクシー", hiragana: "タクシー", meaning: "택시", day: 26 },
  { id: 528, kanji: "テープ", hiragana: "テープ", meaning: "테이프", day: 26 },
  { id: 529, kanji: "テーブル", hiragana: "テーブル", meaning: "테이블", day: 26 },
  { id: 530, kanji: "テスト", hiragana: "テスト", meaning: "시험, 테스트", day: 26 },
  { id: 531, kanji: "デパート", hiragana: "デパート", meaning: "백화점", day: 26 },
  { id: 532, kanji: "テレビ", hiragana: "テレビ", meaning: "텔레비전, TV", day: 26 },

  // ===== Day 27 - Katakana words continued =====
  { id: 533, kanji: "ドア", hiragana: "ドア", meaning: "문 (도어)", day: 27 },
  { id: 534, kanji: "トイレ", hiragana: "トイレ", meaning: "화장실", day: 27 },
  { id: 535, kanji: "ナイフ", hiragana: "ナイフ", meaning: "나이프, 칼", day: 27 },
  { id: 536, kanji: "ネクタイ", hiragana: "ネクタイ", meaning: "넥타이", day: 27 },
  { id: 537, kanji: "ノート", hiragana: "ノート", meaning: "노트, 공책", day: 27 },
  { id: 538, kanji: "パーティー", hiragana: "パーティー", meaning: "파티", day: 27 },
  { id: 539, kanji: "バス", hiragana: "バス", meaning: "버스", day: 27 },
  { id: 540, kanji: "パン", hiragana: "パン", meaning: "빵", day: 27 },
  { id: 541, kanji: "ハンカチ", hiragana: "ハンカチ", meaning: "손수건", day: 27 },
  { id: 542, kanji: "ビル", hiragana: "ビル", meaning: "빌딩", day: 27 },
  { id: 543, kanji: "ペン", hiragana: "ペン", meaning: "펜", day: 27 },
  { id: 544, kanji: "ボールペン", hiragana: "ボールペン", meaning: "볼펜", day: 27 },
  { id: 545, kanji: "ポケット", hiragana: "ポケット", meaning: "주머니", day: 27 },
  { id: 546, kanji: "ボタン", hiragana: "ボタン", meaning: "단추, 버튼", day: 27 },
  { id: 547, kanji: "ホテル", hiragana: "ホテル", meaning: "호텔", day: 27 },
  { id: 548, kanji: "メートル", hiragana: "メートル", meaning: "미터", day: 27 },
  { id: 549, kanji: "ラーメン", hiragana: "ラーメン", meaning: "라면", day: 27 },
  { id: 550, kanji: "ラジオ", hiragana: "ラジオ", meaning: "라디오", day: 27 },
  { id: 551, kanji: "レストラン", hiragana: "レストラン", meaning: "레스토랑", day: 27 },

  // ===== Day 28 - Expressions / 表現 =====
  { id: 552, kanji: "ありがとうございます", hiragana: "ありがとうございます", meaning: "감사합니다", day: 28 },
  { id: 553, kanji: "いいえ", hiragana: "いいえ", meaning: "아니요", day: 28 },
  { id: 554, kanji: "いただきます", hiragana: "いただきます", meaning: "잘 먹겠습니다", day: 28 },
  { id: 555, kanji: "いらっしゃいませ", hiragana: "いらっしゃいませ", meaning: "어서 오세요", day: 28 },
  { id: 556, kanji: "おねがいします", hiragana: "おねがいします", meaning: "부탁드립니다", day: 28 },
  { id: 557, kanji: "おはようございます", hiragana: "おはようございます", meaning: "안녕하세요 (아침)", day: 28 },
  { id: 558, kanji: "お休みなさい", hiragana: "おやすみなさい", meaning: "안녕히 주무세요, 잘 자요", day: 28 },
  { id: 559, kanji: "ごちそうさまでした", hiragana: "ごちそうさまでした", meaning: "잘 먹었습니다", day: 28 },
  { id: 560, kanji: "こちらこそ", hiragana: "こちらこそ", meaning: "저야말로", day: 28 },
  { id: 561, kanji: "ごめんなさい", hiragana: "ごめんなさい", meaning: "미안합니다", day: 28 },
  { id: 562, kanji: "こんにちは", hiragana: "こんにちは", meaning: "안녕하세요 (낮)", day: 28 },
  { id: 563, kanji: "こんばんは", hiragana: "こんばんは", meaning: "안녕하세요 (저녁)", day: 28 },
  { id: 564, kanji: "さようなら", hiragana: "さようなら", meaning: "안녕히 가세요, 안녕", day: 28 },
  { id: 565, kanji: "失礼します", hiragana: "しつれいします", meaning: "실례합니다", day: 28 },
  { id: 566, kanji: "すみません", hiragana: "すみません", meaning: "저기요, 죄송합니다", day: 28 },
  { id: 567, kanji: "どういたしまして", hiragana: "どういたしまして", meaning: "천만에요", day: 28 },
  { id: 568, kanji: "どうぞ", hiragana: "どうぞ", meaning: "어서요, 자, 부디", day: 28 },
  { id: 569, kanji: "はい", hiragana: "はい", meaning: "네, 예", day: 28 },
  { id: 570, kanji: "はじめまして", hiragana: "はじめまして", meaning: "처음 뵙겠습니다", day: 28 },
  { id: 571, kanji: "もしもし", hiragana: "もしもし", meaning: "여보세요 (전화)", day: 28 },
  { id: 572, kanji: "よろしくお願いします", hiragana: "よろしくおねがいします", meaning: "잘 부탁드립니다", day: 28 },
];
